# Generated by codegen_tool

.PHONY: dclean drun dtest dcibuild dbash ddeb dmake

#DOCKER_IMAGE = registry.miranetworks.net/miranetworks/dev_ubuntu_trusty_erlang_17.4
DOCKER_IMAGE = pgdb_tools
DOCKER_CONTAINER_NAME = $(DOCKER_IMAGE)

DOCKER_BUILT = docker/.Dockerfile.built

$(DOCKER_BUILT): docker/Dockerfile
	@docker build -t $(DOCKER_IMAGE) docker/ && touch $(DOCKER_BUILT)

dcibuild: $(DOCKER_BUILT)
	@docker/run $(DOCKER_IMAGE) $(DOCKER_CONTAINER_NAME) "make citest" true 

dtest: $(DOCKER_BUILT)
	@docker/run $(DOCKER_IMAGE) $(DOCKER_CONTAINER_NAME) "make test suite=${suite}" false 

dclean: $(DOCKER_BUILT)
	@docker/run $(DOCKER_IMAGE) $(DOCKER_CONTAINER_NAME) "make clean" true

ddockerclean: 
	@rm -f $(DOCKER_BUILT)

dmake: $(DOCKER_BUILT)
	@docker/run $(DOCKER_IMAGE) $(DOCKER_CONTAINER_NAME) "make" false

drun: $(DOCKER_BUILT)
	@docker/run $(DOCKER_IMAGE) $(DOCKER_CONTAINER_NAME) "make run" false -p 2666:2666 -p 2667:2667 -t

dbash: $(DOCKER_BUILT)
	@docker/run $(DOCKER_IMAGE) $(DOCKER_CONTAINER_NAME) "/bin/bash" false -t

#Example:
#    PPA_DISTRO=ubuntu PPA_RELEASE=trusty make ddeb
ddeb:
	@docker/run registry.miranetworks.net/miranetworks/ppa_${PPA_DISTRO}_${PPA_RELEASE} deb_${PPA_DISTRO}_${PPA_RELEASE}_$(DOCKER_CONTAINER_NAME) "build_deb" true -e PPA_RELEASE=${PPA_RELEASE}
