FROM registry.miranetworks.net/miranetworks/dev_debian_stretch_erlang_20.3

#RUN apt-get clean && \
#    apt-get update && \
#    apt-get install -y some apps

RUN apt-get clean && apt-get update && apt-get install -y postgresql \
                                                          postgresql-contrib
