#!/bin/bash

if [ $# -lt 3 ]; then
    echo "Usage: $0 docker_image docker_container_name command_to_run [docker_options]"
    echo "   Where docker_options are options that can be passed to 'docker run'"
    exit 1
fi

DOCKER_IMAGE=$1
DOCKER_CONTAINER_NAME=$2
DOCKER_COMMAND=$3
shift 3
docker rm -f ${DOCKER_CONTAINER_NAME} 2>/dev/null || true

BASEDIR=/workspace/base

REL=`lsb_release`

if [ $? -eq 0 ]; then
    WRKDIR=`readlink -f $(pwd)`
    docker run \
        --rm=true \
        -i \
        -h devhost \
        --name ${DOCKER_CONTAINER_NAME} \
        -v $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) \
        -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK \
        -w ${BASEDIR} \
        -v ${WRKDIR}:${BASEDIR}  \
        $@ \
        ${DOCKER_IMAGE} ./docker/container_run ${BASEDIR} $(id -u) $(id -g) "${DOCKER_COMMAND}" 
else
    WRKDIR=$(pwd)
    docker run \
        --rm=true \
        -i \
        -h devhost \
        --name ${DOCKER_CONTAINER_NAME} \
        -w ${BASEDIR} \
        -v ${WRKDIR}:${BASEDIR}  \
        $@ \
        ${DOCKER_IMAGE} ${DOCKER_COMMAND}
fi
