#!/bin/bash
WRKDIR=`readlink -f $(pwd)`
docker run --rm=true -i -u="developer" --name pgdb_tools -v $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK -v $(pwd)/../:/workspace/base pgdb_tools $1
docker rm -f pgdb_tools 2>/dev/null  || true
